#!/usr/bin/env ruby

require 'optparse'
require 'captains_mistress/app'

args = ARGV.clone

options = {}

OptionParser.new do |opts|
  opts.banner = 'Usage: captains_mistress [options]'

  opts.on('-v', '--[no-]verbose', 'Run verbosely') do |v|
    options[:verbose] = v
  end

  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end

  opts.on_tail('--version', 'Show version') do
    puts CaptainsMistress::VERSION
    exit
  end

  opts.on('--width NUM', Integer, 'Set width of game board') do |w|
    options[:width] = w
  end

  opts.on('--height NUM', Integer, 'Set height of game board') do |h|
    options[:height] = h
  end

  opts.on('--length LEN', Integer, 'Set length of winning streak') do |l|
    options[:length] = l
  end

  opts.on('--strict', 'Require winning streak be exact length') do |s|
    options[:strict] = s
  end

end.parse!(args)

CaptainsMistress::App.new(options).run
